### PR TITLE
Fixes #38

### LINKED ISSUE #38: Railcraft Tank Support
Now that @CovertJaguar has released the version of RC which fixes the contents of tanks not properly synching with the client, the WAILA tooltip no longer shows the correct information. It just displays 0/X all of the time. I'm guessing he renamed the field/property? Either way, it doesn't work.

### PR DESCRIPTION
**Pull request by Timeslice42**
This is more in line with how railcraft is doing this now. WARNING: I do not have a build environment, so this hasn't been tested.

### CODE REVIEW

**Comment by tterrag1098** [comment]
I don't think this will be reliable, as a general rule I don't rely on any clientside data as how the mod syncs is very arbitrary. It could change between versions even. I will fix this another way.

**Comment by Timeslice42** [comment]
This code is from a hack that @CovertJaguar had to implement to get around a recent forge bug. I can't reliably speak to whether it's actually client-side only, but it could quite likely change in the future.

**Comment by CovertJaguar** [comment]
Its been a while, but I believe that the renderData is correctly sync'd to the client for the Iron/Steel Tanks and Fluid Loader/Unloader. But this does not hold true for any of my other blocks as only the blocks that actually need this data send it to the client.

**Comment by tterrag1098** [comment]
I've already fixed this here 8df1aa412ff08c48949639eede3b9485092319f2

**Comment by Timeslice42** [comment]
Has this been released? I don't remember where your jenkins is.

**Comment by tterrag1098** [comment]
Yes, it's on curseforge.

**Pull request closed without merging**
